
export const authActions = {
  SIGNUPINITIATE: 'SIGNUPINITIATE',
  SIGNUPSUCCESS:  'SIGNUPSUCCESS',
  SIGNUPFAILURE:  'SIGNUPFAILURE',
  LOGININITIATE: 'LOGININITIATE',
  LOGINSUCCESS: 'LOGINSUCCESS',
  LOGINFAILURE: 'LOGINFAILURE',
  LOGOUTINITIATE: 'LOGOUTINITIATE',
  LOGOUTSUCCESS: 'LOGOUTSUCCESS',
  LOGOUTFAILURE: 'LOGOUTFAILURE'
}

export const productActions = {
  GET_ALL_PRODUCTS_INITIATE: 'GET_ALL_PRODUCTS_INITIATE',
  GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
  GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
  GET_SINGLE_PRODUCT_INITIATE: 'GET_SINGLE_PRODUCT_INITIATE',
  GET_SINGLE_PRODUCT_SUCCESS: 'GET_SINGLE_PRODUCT_SUCCESS',
  GET_SINGLE_PRODUCT_FAILURE: 'GET_SINGLE_PRODUCTFAILUREE',
  CLEAR_SINGLE_PRODUCT: 'CLEAR_SINGLE_PRODUCT'
}

export const cartActions = {
  GET_CART_ITEMS_INITIATE: 'GET_CART_ITEMS_INITIATE',
  GET_CART_ITEMS_SUCCESS: 'GET_CART_ITEMS_SUCCESS',
  GET_CART_ITEMS_FAILURE: 'GET_CART_ITEMS_FAILURE',

  // single product fetch in cart
  FETCH_CART_PRODUCT_INITIATE: 'FETCH_CART_PRODUCT_INITIATE',
  FETCH_CART_PRODUCT_SUCCESS: 'FETCH_CART_PRODUCT_SUCCESS',
  FETCH_CART_PRODUCT_FAILURE: 'FETCH_CART_PRODUCT_FAILURE'

}